Imagem de erro
Kaoticz/Nekollector pull request #26
Opened 2024-11-20 22:27 UTC by JFernandoHL

2024-11-20 23:49 UTC, Kaoticz requested changes

2024-11-20 23:49 UTC, Kaoticz commented on pom.xml
> +      </dependency>
Essa dependência faz o que?

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Imagens", "*.png", "*.jpg", "*.jpeg"));
As extensões não estão funcionando aqui. Aparece como uma lista sem opções para mim.

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            }
Esse código salva um arquivo vazio pra mim.

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            this.downloadButton.setDisable(true);
Isso não é necessário, todos os botões são desabilitados quando a aplicação inicia.

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +        Platform.runLater(() -> this.downloadButton.setDisable(true));
Não é necessário, `loadNextImage()` já lida com a ativação e desativação dos botões.

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +                    Platform.runLater(() -> this.downloadButton.setDisable(false));
Não é necessário, `loadNextImage()` já lida com a ativação e desativação dos botões.

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/common/Statics.java
> +    public static final Image ERROR_IMAGE = new Image(Statics.class.getResource("/assets/images/erro.png").toExternalForm());
Há algum motivo para carregar a imagem dessa forma quando o IDE sugere uma maneira mais segura?
![image](https://github.com/user-attachments/assets/ed9c49e6-7256-4da8-87d3-36b3a532bb75)

2024-11-20 23:49 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/common/Statics.java
> +    public static final Image ERROR_IMAGE = new Image(Statics.class.getResource("/assets/images/erro.png").toExternalForm());
Você também esqueceu de carregar a imagem em `loadNextImage()`, no local marcado pelo TODO.

2024-11-21 00:31 UTC, JFernandoHL commented on pom.xml
> +      </dependency>
É para o método de BufferedImage funcionar, se não tem que fazer manualmente a conversão da imagem

2024-11-21 00:33 UTC, JFernandoHL commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Imagens", "*.png", "*.jpg", "*.jpeg"));
Pra mim tá normal aqui...

2024-11-21 00:33 UTC, JFernandoHL commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            }
Que nem respondi ali em cima, para mim tá funcionando normal, não sei prq estaria dando erro

2024-11-21 00:35 UTC, JFernandoHL commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +        Platform.runLater(() -> this.downloadButton.setDisable(true));
Ok, fiz todos esses porque no issue falava que era necessário o botão de download desativar nessas instâncias, então assumi que o programa ainda não fazia algo do tipo

2024-11-21 16:17 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Imagens", "*.png", "*.jpg", "*.jpeg"));
Pode ser um bug do JavaFX em Linux. Vou investigar mais a fundo.

2024-11-21 16:19 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            }
Descobri que se eu colocar a extensão do arquivo manualmente no *file picker*, a imagem é salva corretamente.
Pode ter relação com o problema dos filtros de extensão do JavaFX não funcionarem direito no Linux.

2024-11-21 16:52 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            }
Descobri que ele não salva arquivos `.jpg` corretamente, somente `.png`.

2024-11-21 16:57 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            }
Confirmado, a implementação do `ImageIO` do OpenJDK não possui um encoder para `.jpg`.
https://stackoverflow.com/questions/3432388/imageio-not-able-to-write-a-jpeg-file

2024-11-21 17:04 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Imagens", "*.png", "*.jpg", "*.jpeg"));
O filtro funciona corretamente se você defini-lo através do método `setSelectedExtensionFilter()`.

2024-11-21 17:14 UTC, Kaoticz commented on src/main/java/com/github/kaoticz/nekollector/MainController.java
> +            }
Resolvi salvando imagens jpg como png.

2024-11-21 17:37 UTC, Kaoticz approved these changes

2024-11-21 17:38 UTC, merged